In [1]:
import numpy as np
print(np.__version__)

2.4.0


## Creating arrays
ref: [text](https://numpy.org/doc/stable/user/basics.creation.html)

In [8]:
# From a python list

python_list = [1,2,3,4,5]
type(python_list)

list

In [6]:
list_array = np.array(python_list)
list_array

array([1, 2, 3, 4, 5])

In [7]:
type(list_array)

numpy.ndarray

In [ ]:
# ref: https://numpy.org/doc/stable/reference/generated/numpy.array.html

# confirm the data type of an array

list_array.dtype

dtype('int64')

In [10]:
demo_list = [1,2,'Ann']
demo_array = np.array(demo_list)
demo_array

array(['1', '2', 'Ann'], dtype='<U21')

In [11]:
# explicitly passing in the data type

float_list = [1.2,2.5,3.5]
float_array = np.array(float_list, dtype='float')
float_array.dtype

dtype('float64')

## np.arange

In [12]:
arr = np.arange(9)
print(arr)
type(arr)

[0 1 2 3 4 5 6 7 8]


numpy.ndarray

## zeros and ones
#### shape
2-dimen: (rows,columns) e.g. 2,2 means 2 rows 2 columns
3-dimen: (rows,columns,_)

In [13]:
np.ones(1)

array([1.])

In [14]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [15]:
np.ones((2,2),dtype="int")

array([[1, 1],
       [1, 1]])

In [16]:
np.zeros((4,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [17]:
np.zeros((4,5),dtype="int")

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

## np.linspace

In [20]:
# creates an arrays of x elements, btn a and b, evenly distributed
# np.linspace(a.b.x)

np.linspace(3,10,5)

array([ 3.  ,  4.75,  6.5 ,  8.25, 10.  ])

In [19]:
np.linspace(3,10,5,endpoint=False)  # ignores b(the last number)

array([3. , 4.4, 5.8, 7.2, 8.6])

In [ ]:
np.linspace(3,5,2,endpoint=False,dtype='int')   # the dtype 'int' means it rounds off

array([3, 4])

## np.full

In [22]:
np.full((2,3),2,dtype='int')

array([[2, 2, 2],
       [2, 2, 2]])

In [23]:
np.full((2,3,4),3,dtype='float')

array([[[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]],

       [[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]]])

In [24]:
np.full((3,4,5),3,dtype='float')

array([[[3., 3., 3., 3., 3.],
        [3., 3., 3., 3., 3.],
        [3., 3., 3., 3., 3.],
        [3., 3., 3., 3., 3.]],

       [[3., 3., 3., 3., 3.],
        [3., 3., 3., 3., 3.],
        [3., 3., 3., 3., 3.],
        [3., 3., 3., 3., 3.]],

       [[3., 3., 3., 3., 3.],
        [3., 3., 3., 3., 3.],
        [3., 3., 3., 3., 3.],
        [3., 3., 3., 3., 3.]]])

# Random number generation
## np.random.random

In [26]:
np.random.random((2,3))

array([[0.44874326, 0.71136489, 0.80482544],
       [0.83864156, 0.70397687, 0.78032854]])

In [ ]:
# (low,high,size,dtype)
# value passed as low CAN be part of the result
# value passed as high is always excluded

np.random.randint(10,20,(2,3))

array([[18, 12, 10],
       [17, 15, 19]], dtype=int32)

In [28]:
np.random.randint(10,20,5)

array([16, 11, 12, 13, 13], dtype=int32)

In [ ]:
# creates an array with elements from a normal distribution
# takes params (loc, scale, (shape))

np.random.normal(5,1,(2,3))

array([[5.77205043, 6.24911964, 4.28384091],
       [4.99394683, 5.91831651, 5.86406889]])

## np.eye

In [31]:
np.eye(3,dtype='int')

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [32]:
np.eye(4,3,dtype='int')

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1],
       [0, 0, 0]])

## Creating custom arrays
- attributes: dimensions, shape, size(product of shape), dtype

In [ ]:
arr = np.array([1,2,3,4,5], dtype = 'int')

In [35]:
# 3 by 3
# from innermost to outermost

arr = np.array([[1,2,3],[4,5,6],[7,8,9]], dtype = 'int')
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [36]:
arr.ndim

2

In [37]:
arr.shape

(3, 3)

In [38]:
arr.size

9

In [39]:
arr.dtype

dtype('int64')

In [ ]:
# 3 rows, 3 columns, 3 layers

np.array()

TypeError: array() takes from 1 to 2 positional arguments but 3 were given