# Reshaping arrays

In [2]:
import numpy as np

In [3]:
arr = np.array([[1,2,3],[4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
arr.shape

(2, 3)

In [5]:
arr.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [6]:
arr.reshape(6,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

# Concatenation
no. of input columns must match when concatenating along rows, except when flattening the output

In [7]:
arr = np.array([1,2,3])
arr1 = np.array([[1,2,3]]) # must have multiple dimensions
arr2 = np.array([[4,5,6]])

In [8]:
arr.shape

(3,)

In [9]:
arr1.shape

(1, 3)

In [10]:
arr2.shape

(1, 3)

In [11]:
# concat along rows

arr3 = np.concatenate((arr1,arr2))
arr3

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
arr4 = np.concatenate((arr1,arr2), axis=None)   # flattened output
arr4

array([1, 2, 3, 4, 5, 6])

In [13]:
# concat along columns

arr5 = np.concatenate((arr1,arr2), axis=1)
arr5

array([[1, 2, 3, 4, 5, 6]])

# Mathematical operations

In [14]:
# add 1 to all elements in a list
num = [1,2,3,4]
value = 1

arr = np.array(num)
arr + 1

array([2, 3, 4, 5])

In [15]:
arr - 1

array([0, 1, 2, 3])

In [16]:
arr * 3

array([ 3,  6,  9, 12])

In [17]:
arr ** 3

array([ 1,  8, 27, 64])

In [18]:
arr / 3

array([0.33333333, 0.66666667, 1.        , 1.33333333])

In [3]:
first = np.array([1,2,3])
second = np.array([4,5,6])

print(first + second)
print(first - second)
print(first * second)
print(first / second)
print(first ** second)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[  1  32 729]


## Check how long operations take

In [19]:
import time

In [20]:
size = 10**7

python_list = list(range(size))
numpy_array = np.array(python_list)

In [21]:
len(python_list)

10000000

In [22]:
numpy_array.size

10000000

In [23]:
start_time = time.time()
python_list_sum = sum(python_list)
end_time = time.time()

python_list_time = end_time - start_time
python_list_time

0.1562647819519043

In [24]:
start_time = time.time()
numpy_list_sum = np.sum(numpy_array)
end_time = time.time()

numpy_array_time = end_time - start_time
numpy_array_time

0.01739501953125

In [25]:
arr

array([1, 2, 3, 4])

In [26]:
# summ all elements

np.sum(arr)

np.int64(10)

In [28]:
np.max(arr)

np.int64(4)

In [29]:
np.min(arr)

np.int64(1)

In [27]:
np.mean(arr)

np.float64(2.5)

In [30]:
np.median(arr)

np.float64(2.5)

# Vectorisation
Accessing elements within arrays

In [32]:
list_1 = [1,2,3,4,5,6]
list_2 = [6,5,3,2,4,5]

In [33]:
# adding 

result = []

for i in range(len(list_1)):
    result.append(list_1[i] + list_2[1])

print(result)

[6, 7, 8, 9, 10, 11]


# Broadcasting
Broadcasting is how NumPy lets arrays of different shapes (multidimensional data) work together without copying data. It 'stretches' the smaller array to match the larger one.
When comparing shapes from right to left:
- Dimensions must be equal, or
- One of them must be 1, or
- One dimension can be missing
If not → ❌ error

In [ ]:
# 1d

arr = np.array([1,2,3])
arr + 10    # 10 is a scalar and is treated as [10,10,10]

array([11, 12, 13])

In [ ]:
# 2d



In [ ]:
# 3d

