# Sorting arrays

In [1]:
import numpy as np

In [4]:
# sort 1d

a = np.array([8,2,6,4,5])
np.sort(a)

array([2, 4, 5, 6, 8])

In [7]:
# sort 2d

b = np.array([[23,15,7],[11,19,78],[3,89,73]])
b

array([[23, 15,  7],
       [11, 19, 78],
       [ 3, 89, 73]])

In [ ]:
np.sort(b)

# default is axis = 1

array([[ 7, 15, 23],
       [11, 19, 78],
       [ 3, 73, 89]])

In [9]:
# to sort and flatten

np.sort(b, axis=None)

array([ 3,  7, 11, 15, 19, 23, 73, 78, 89])

In [10]:
# to sort along columns

np.sort(b, axis = 0)

array([[ 3, 15,  7],
       [11, 19, 73],
       [23, 89, 78]])

In [ ]:
# sort in descending order

np.sort(b, axis = None)[::-1]

array([89, 78, 73, 23, 19, 15, 11,  7,  3])

In [14]:
# return the indices of the items

c = np.array([12,87,54,234,56])
np.argsort(c)

array([0, 2, 4, 1, 3])

# Partitioning

In [21]:
d = np.random.randint(2,678,10)
d

array([359,  86, 236, 213, 475, 363, 278, 613, 273, 267], dtype=int32)

In [23]:
# np.partition('','index of boundary')

np.partition(d,5)

array([ 86, 213, 236, 267, 273, 278, 359, 363, 475, 613], dtype=int32)

In [ ]:
# excercise: partitioning along a specific axis (2d): axis = ?

# Accessing specific elements

In [25]:
e = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
e

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [27]:
# access and slice i.e. array[row, col]

e[1,1]

np.int64(6)

In [ ]:
# : means everything else

e[1,:]

array([5, 6, 7, 8])

In [30]:
e[:,3]

array([ 4,  8, 12, 16])

In [31]:
e[:,:]

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [ ]:
e[0:2,:]

# returns all rows btn index 0 and index 2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [34]:
e[1:2,:]

array([[5, 6, 7, 8]])

In [35]:
e[:,2:3]

array([[ 3],
       [ 7],
       [11],
       [15]])

In [36]:
e[1:3,1:3]

array([[ 6,  7],
       [10, 11]])

In [37]:
# start index, stop index, step size

e

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [38]:
e[1,0:4:2]

# step size skips indices

array([5, 7])

In [39]:
e[1,0::2]

array([5, 7])

In [40]:
e[0:4:3,2]

array([ 3, 15])

In [ ]:
# return 2,4 and 10,12

e[]