# Numpy Exercise 5

### All of the questions in this exercise are attributed to rougier/numpy-100

In [1]:
import numpy as np

#### 61. Find the nearest value from a given value in an array (★★☆)

In [5]:
arr61 = np.array([1.2, 2.5, 3.8, 4.1, 5.9])
given_value = 4

nearest = arr61[np.abs(arr61-given_value).argmin()]

# np.abs(arr61-given_value)      # distance from given value
# .argmin()          # index of smallest distance

nearest

np.float64(4.1)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [6]:
A = np.random.uniform(0,1,(1,3))
B = np.random.uniform(0,1,(3,1))

it = np.nditer([A,B,None])
for x,y,z in it: z[...] = x + y

print(it.operands[2])

[[0.68382325 1.09431766 0.94256746]
 [0.75228062 1.16277503 1.01102484]
 [0.520946   0.93144041 0.77969021]]


#### 63. Create an array class that has a name attribute (★★☆)

In [7]:
class NamedArray(np.ndarray):
    def __new__(cls, input_array, name="no name"):
        obj = np.asarray(input_array).view(cls)
        obj.name = name
        return obj

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [8]:
vec = np.array([1,2,3,4])
indices = np.array([0,2,2,3])
np.add.at(vec, indices, 1)
vec

array([2, 2, 5, 5])

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [12]:
X = [1,2,3,4,5,6]
I = [0,1,2,0,1,2]

F = np.zeros(5)
np.add.at(F, I, X)
F

array([5., 7., 9., 0., 0.])

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

In [13]:
image = np.random.randint(0,256,(100,100,3), dtype=np.ubyte)
colors = image.view(dtype=np.dtype((np.void, image.dtype.itemsize * image.shape[2]))).reshape(image.shape[0]*image.shape[1])
unique_colors = np.unique(colors)
unique_colors

array([b'\x00\x03\xB3', b'\x00\x1B\x06', b'\x00\x1F\x37', ...,
       b'\xFF\xF7\x33', b'\xFF\xF8\xA1', b'\xFF\xFD\x17'],
      shape=(9995,), dtype='|V3')

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [14]:
arr4d = np.random.random((3,4,3,4))
arr4d_sum = arr4d.sum(axis=(-2,-1))
arr4d_sum

array([[6.35614633, 5.71174577, 4.95219494, 6.84612134],
       [6.10275385, 5.59162545, 7.02551533, 5.54482075],
       [6.54297024, 6.90741031, 5.25256933, 6.82833666]])

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

In [15]:
D = np.random.randn(100)
S = np.random.randint(0,10,100)
D_means = np.array([D[S==k].mean() for k in range(10)])
D_means

array([ 0.3045847 ,  0.27602833, -0.33437639, -0.18823082,  0.08228618,
        0.04593555, -0.07967342,  0.25600914, -0.1498524 , -0.24611811])

#### 69. How to get the diagonal of a dot product? (★★★)

In [16]:
A = np.random.uniform(0,1,(3,3))
B = np.random.uniform(0,1,(3,3))
np.diag(np.dot(A, B))

array([0.92080057, 0.30512329, 1.26483312])

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [17]:
Z = np.zeros(3*5 + 2, dtype=int)
Z[::4] = np.arange(1,6)
Z

array([1, 0, 0, 0, 2, 0, 0, 0, 3, 0, 0, 0, 4, 0, 0, 0, 5])

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

In [18]:
A = np.random.uniform(0,1,(5,5,3))
B = np.random.uniform(0,1,(5,5))
C = A * B[:,:,np.newaxis]
C

array([[[0.45492051, 0.32641143, 0.02738531],
        [0.02369266, 0.04985681, 0.02461411],
        [0.18671888, 0.44813164, 0.29026809],
        [0.08034446, 0.53651639, 0.59600608],
        [0.43749179, 0.24444883, 0.04339039]],

       [[0.00583382, 0.35252155, 0.70965811],
        [0.49149912, 0.26145702, 0.37120032],
        [0.08189561, 0.82244182, 0.45205001],
        [0.2954843 , 0.14692425, 0.12026339],
        [0.0872545 , 0.03817201, 0.09975394]],

       [[0.22439199, 0.3660326 , 0.49324799],
        [0.12869913, 0.11919578, 0.10004406],
        [0.16940412, 0.15890058, 0.15995819],
        [0.61394502, 0.46232543, 0.02958216],
        [0.59921312, 0.26761921, 0.61315326]],

       [[0.14637171, 0.08107578, 0.10867892],
        [0.2917683 , 0.25674884, 0.3900326 ],
        [0.02271334, 0.30969674, 0.24156368],
        [0.83016925, 0.70070687, 0.23547351],
        [0.01894786, 0.12996304, 0.04690293]],

       [[0.15368068, 0.0532371 , 0.19662098],
        [0.66289725, 0.535

#### 72. How to swap two rows of an array? (★★★)

In [19]:
A = np.arange(25).reshape(5,5)
A[[0,1]] = A[[1,0]]
A

array([[ 5,  6,  7,  8,  9],
       [ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

In [20]:
triangles = np.random.randint(0,100,(10,3))
lines = np.sort(triangles[:,[[0,1],[1,2],[0,2]]], axis=2).reshape(-1,2)
unique_lines = np.unique(lines, axis=0)
unique_lines

array([[ 2, 74],
       [ 2, 88],
       [ 3,  4],
       [ 3, 93],
       [ 4, 93],
       [ 5,  8],
       [ 5, 10],
       [ 6, 27],
       [ 6, 53],
       [ 8, 10],
       [ 9, 11],
       [ 9, 39],
       [11, 39],
       [11, 65],
       [17, 19],
       [17, 49],
       [19, 49],
       [21, 37],
       [21, 46],
       [26, 62],
       [26, 76],
       [27, 41],
       [27, 53],
       [27, 55],
       [37, 46],
       [39, 65],
       [41, 55],
       [62, 76],
       [74, 88]], dtype=int32)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

In [21]:
C = np.bincount([0,1,1,3,2,1,0,0,0,2])
A = np.repeat(np.arange(len(C)), C)
A

array([0, 0, 0, 0, 1, 1, 1, 2, 2, 3])

#### 75. How to compute averages using a sliding window over an array? (★★★)

In [22]:
def moving_average(a, n=3):
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
a = np.random.uniform(1,10,20)
moving_average(a, n=3)

array([6.82256458, 5.56037178, 5.51609844, 5.38522363, 6.22314779,
       3.75728716, 3.77707702, 3.37581209, 4.0987377 , 3.62076931,
       4.16168906, 5.63752804, 7.62717141, 8.70219817, 7.3913089 ,
       8.08507635, 5.33615864, 6.12919998])

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

In [23]:
Z = np.arange(10)
N = 3
def sliding_window(a, window_size):
    shape = (a.size - window_size + 1, window_size)
    strides = (a.strides[0], a.strides[0])
    return np.lib.stride_tricks.as_strided(a, shape=shape, strides=strides)
sliding_window(Z, N)

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4],
       [3, 4, 5],
       [4, 5, 6],
       [5, 6, 7],
       [6, 7, 8],
       [7, 8, 9]])

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

In [24]:
A = np.array([1.0, -2.0, 3.0, -4.0])
np.negative(A, out=A)
A

array([-1.,  2., -3.,  4.])

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)