# Numpy Exercise 2

### All of the questions in this exercise are attributed to rougier/numpy-100

In [1]:
import numpy as np
print (np.__version__)

2.4.0


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [2]:
arr16 = np.random.randint(5, 25, (5,5), dtype="int")
np.pad(arr16, (1,1), mode="constant", constant_values=(0,0))

array([[ 0,  0,  0,  0,  0,  0,  0],
       [ 0, 22, 23, 17, 21, 14,  0],
       [ 0, 19, 19, 11,  8,  6,  0],
       [ 0,  6, 15, 10, 15, 11,  0],
       [ 0,  5, 13,  9, 22, 18,  0],
       [ 0, 12, 12,  7,  8, 21,  0],
       [ 0,  0,  0,  0,  0,  0,  0]])

#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [ ]:
# Each of these expressions has a different result

0 * np.nan          # result = nan
np.nan == np.nan    # can't be equal to itself, so result = False
np.inf > np.nan     # result = False
np.nan - np.nan     # result = nan
np.nan in set([np.nan])     # result = True
0.3 == 3 * 0.1      # result = False, bc the 0.3 float is an approximation, not exact

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [ ]:
np.diag([1,2,3,4], k=-1)    # 'k' here meaning one lower than the main diag


array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [ ]:
arr19 = np.zeros((8,8), dtype="int")

arr19[::2,1::2] = 1
arr19[1::2,::2] = 1

arr19


array([[0, 1, 0, 1, 0, 1, 0, 1],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 0, 0, 0, 0, 0, 0, 0]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [17]:
arr20 = np.zeros((6,7,8), dtype='int')
np.unravel_index(99, (6,7,8))

(np.int64(1), np.int64(5), np.int64(3))

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [19]:
arr21 = np.array([[0,1],[1,0]])
np.tile(arr21, (4,4))

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 22. Normalize a 5x5 random matrix (★☆☆)

In [ ]:
# normalization is scaling the values of an array to a specific range, typically between 0 and 1, to ensure that numerical data attributes have the same scale. This prevents models from being biased towards variables with higher magnitudes.
# (arr - np.min(arr)) / (np.max(arr) - np.min(arr))

arr22 = np.random.random((5,5))
arr22_norm = (arr22 - arr22.min()) / (arr22.max() - arr22.min())
arr22_norm

array([[0.57516147, 0.89781352, 0.83466576, 0.77979229, 0.29582564],
       [0.31051285, 0.97590937, 0.        , 0.63901513, 0.88382485],
       [0.55811121, 0.10741446, 0.40419159, 0.68525298, 0.96701633],
       [0.40525298, 0.10654384, 0.04331629, 0.48041568, 0.95455234],
       [0.30530326, 0.29684319, 1.        , 0.14138189, 0.55066652]])

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [25]:
# buiding custom dtypes enables you to build structured arrays with specific data formats tailored to your needs.
# 1byte = 8bits: use uint8 for each of the 4 names (4bytes per colour)

custom_dtype = np.dtype([('R', np.uint8), ('G', np.uint8), ('B', np.uint8), ('A', np.uint8)])

# using the customer dtype, then access one of the channels
colors = np.array([(255, 0, 0, 255),(0, 255, 0, 255),(0, 0, 255, 128)], dtype=custom_dtype)

colors['R']

array([255,   0,   0], dtype=uint8)

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [ ]:
# Matrix multiplication rule: (m × n) @ (n × p) → (m × p)

arr53 = np.full((5,3), 5, dtype='int')
arr32 = np.full((3,2), 3, dtype='int')

arr53 @ arr32

array([[45, 45],
       [45, 45],
       [45, 45],
       [45, 45],
       [45, 45]])

In [34]:
np.matmul(arr53, arr32)

array([[45, 45],
       [45, 45],
       [45, 45],
       [45, 45],
       [45, 45]])

In [ ]:
np.dot(arr53, arr32)    # for 1D arrays, works differently

array([[45, 45],
       [45, 45],
       [45, 45],
       [45, 45],
       [45, 45]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [ ]:
arr25 = np.array([1,2,3,4,5,6,7,8,9,10])

# modify existing array, not create a new one
# use boolean masking (select elements based on a bool condition)

mask = (arr25>3) & (arr25<8)
arr25[mask] *= -1

In [37]:
arr25

array([ 1,  2,  3, -4, -5, -6, -7,  8,  9, 10])

#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

The first print statement uses python's default `sum` and `range` functions, while after the `from numpy import *`, the `sum` used is numpy's `np.sum` i.e.
- `range(5)` results in `0,1,2,3,4`
- the first does `0+1+2+3+4` (which = 10), then `-1`(which = 9) and the result is `9`
- the second treats the `range` output as a 1D array, and the `-1` means that the `sum` works on the last axis so `0+1+2+3+4` means the result is `10`

In [39]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [40]:
Z = np.array([1,2,3,4,5])

In [ ]:
Z**Z    # valid bc [1*1, 2*2, 3*3, 4*4, 5*5]

array([   1,    4,   27,  256, 3125])

In [ ]:
2 << Z >> 2 # valid bitwise operator 2 << [1,2,3] → [4, 8, 16] [4,8,16] >> 2 → [1,2,4]


array([ 1,  2,  4,  8, 16])

*Bitwise operators*

Performs operations at the level of the string/arrays' individual bits, with an order of operations following: () then ~ - then * / % then + - then << >> then & then ^ then |.
- `AND/np.bitwise_and()`
- `OR/np.bitwise_or()`
- `XOR/np.bitwise_xor()`
- `NOT/np.invert()`
- `np.left_shift()` → shifts Z left using the `<<`
- `np.right_shift()`    → shifts Z right using the `>>`

In [ ]:
Z <- Z  # not valid as <- is not an operator
# could be seen as Z < -Z, but that's a comparison and returns 'False' for each element since it can't be less than its negative

array([False, False, False, False, False])

In [ ]:
1j*Z    # valid: 'ij' is a complex number, so multiplication is possible

array([0.+1.j, 0.+2.j, 0.+3.j, 0.+4.j, 0.+5.j])

In [ ]:
Z/1/1   #yup! divided Z left to right by 1, results are floats

array([1., 2., 3., 4., 5.])

In [ ]:
Z<Z>Z   # not valid: chained comparisons allowed in python, but not numpy

#### 28. What are the result of the following expressions?
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [ ]:
np.array(0) / np.array(0)

# this is dividing by 0, bc 0/0 is nan
# result is runtime error with the value float64(nan)

C:\Users\HP\AppData\Local\Temp\ipykernel_12796\873513115.py:1: RuntimeWarning: invalid value encountered in divide
  np.array(0) / np.array(0)


np.float64(nan)

In [ ]:
np.array(0) // np.array(0)

# dividing by 0 affects the int floor division still
# result is runtimewarning with value int64(0)

C:\Users\HP\AppData\Local\Temp\ipykernel_12796\2018018105.py:1: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)


np.int64(0)

In [ ]:
np.array([np.nan]).astype(int).astype(float)

# trying to convert a nan into an int isn't possible
# result is the smallest possible int, that is then converted to a float i.e. -9.22337204e+18

C:\Users\HP\AppData\Local\Temp\ipykernel_12796\699728972.py:1: RuntimeWarning: invalid value encountered in cast
  np.array([np.nan]).astype(int).astype(float)


array([-9.22337204e+18])

#### 29. How to round away from zero a float array ? (★☆☆)

In [ ]:
# round to the nearest full no
# +ve no.s -> round up (e.g. 0.5 to 1), -ve no.s -> round down (e.g. -0.5 to -1)

arr29 = np.array([1.5, 2.5, -1.5, -2.5])

# use a boolean mask
mask = (arr29 > 0)

arr29_rounded = np.where(mask, np.ceil(arr29), np.floor(arr29))
# np.where(condition, if true choose x, else choose y)

arr29_rounded

array([ 2.,  3., -2., -3.])

#### 30. How to find common values between two arrays? (★☆☆)

In [ ]:
arr301 = np.array([1, 2, 3, 4, 5])
arr302 = np.array([4, 5, 6, 7])

# np.intersect1d(a, b) returns only elements in both
# for higher D arrays, flatten first i.e. np.ravel()
common = np.intersect1d(arr301, arr302)
print(common)

[4 5]
