# Numpy Exercise 1

### All of the questions in this exercise are attributed to rougier/numpy-100

#### 1. Import the numpy package under the name `np` (★☆☆)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [2]:
print(np.__version__)

2.4.0


#### 3. Create a null vector of size 10 (★☆☆)

In [3]:
null_v = np.zeros(10, dtype="int")
null_v

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

#### 4. How to find the memory size of any array (★☆☆)

In [4]:
null_v.itemsize

8

#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [ ]:
# using jupyter notebooks

help(np.add)

Help on ufunc in module numpy:

add = <ufunc 'add'>
    add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

    Add arguments element-wise.

    Parameters
    ----------
    x1, x2 : array_like
        The arrays to be added.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array wi

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [7]:
arr6 = np.zeros(10, dtype="int")
arr6[5] = 1
arr6

array([0, 0, 0, 0, 0, 1, 0, 0, 0, 0])

#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [8]:
arr7 = np.arange(10,50)
arr7

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [9]:
arr8 = np.arange(1,11)
arr8_flipped = np.flip(arr8)
arr8_flipped

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [10]:
np.sort(arr8, axis = None)[::-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [11]:
arr9 = np.arange(0,9).reshape((3,3))
arr9

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [12]:
list10 = [1,2,0,0,4,0]
arr10 = np.array(list10)
np.nonzero(arr10)

(array([0, 1, 4]),)

#### 11. Create a 3x3 identity matrix (★☆☆)

In [13]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [14]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [15]:
np.random.random((3,3,3))

array([[[0.47326803, 0.82353891, 0.36083319],
        [0.39983749, 0.97448746, 0.07898197],
        [0.50487729, 0.14157514, 0.73450903]],

       [[0.79373798, 0.17480328, 0.35418628],
        [0.40763944, 0.66526602, 0.27550277],
        [0.55830433, 0.95409178, 0.24591926]],

       [[0.8461386 , 0.27307282, 0.84163929],
        [0.34600584, 0.48674492, 0.97514112],
        [0.47363326, 0.99668561, 0.87101525]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [20]:
arr13 = np.random.random((10,10))
print(arr13)

print(np.max(arr13))
print(np.min(arr13))

[[0.37159182 0.81373686 0.44304664 0.22990797 0.65367732 0.6447836
  0.46577518 0.20546568 0.63847102 0.48668705]
 [0.74559323 0.43383336 0.65937675 0.38827315 0.27770936 0.84594787
  0.57879338 0.27562105 0.48709124 0.01857562]
 [0.286652   0.91095343 0.98094317 0.98573055 0.94397761 0.39911571
  0.14986142 0.15273797 0.53379865 0.71816572]
 [0.6375699  0.87126717 0.28170487 0.50303015 0.41794987 0.97747448
  0.95667046 0.95182876 0.24260813 0.55045978]
 [0.84446976 0.38276741 0.5342203  0.08011948 0.90451879 0.12774177
  0.02496155 0.34828009 0.89767217 0.01781402]
 [0.75818897 0.21890414 0.32023752 0.31180437 0.88712557 0.3047423
  0.95663064 0.23628126 0.63143735 0.25287583]
 [0.39039131 0.24557525 0.05453213 0.70861535 0.65033866 0.9567867
  0.23760178 0.56203455 0.53965359 0.37641941]
 [0.16539533 0.33115687 0.65142701 0.2042677  0.34217918 0.85831203
  0.78718158 0.78558261 0.03726041 0.64542935]
 [0.51818159 0.14303175 0.58885092 0.34768375 0.76349935 0.166351
  0.7949281  0.84

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [26]:
arr14 = np.random.randint(0,100,30)
print(arr14)

np.mean(arr14)

[30 85  6 78 73 74 93 16 55 20 32 55  0  0 31 14  6 32 51 75 20 33 77 39
 72  7 77 24 41 35]


np.float64(41.7)

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [52]:
arr15 = np.zeros((5,5), dtype="int")
np.pad(arr15, (1,1), mode="constant", constant_values=(1,1))

array([[1, 1, 1, 1, 1, 1, 1],
       [1, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 1],
       [1, 1, 1, 1, 1, 1, 1]])